In [1]:
for i in range(450, 751):
    print(i, end=",")

450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,

In [5]:
for i in range(64, 76, 1):
    print(i, end=",")

64,65,66,67,68,69,70,71,72,73,74,75,

In [9]:
for i in range(165, 251, 5):
    print(i, end=",")

165,170,175,180,185,190,195,200,205,210,215,220,225,230,235,240,245,250,

In [1]:
for i in range(101, 112, 1):
    print(i, end=",")

101,102,103,104,105,106,107,108,109,110,111,

In [1]:
import pandas as pd

excel_valid = r"./phos_sensor_reg_data.txt"
df_valid = pd.read_csv(excel_valid, index_col=None, sep=",")
df_valid.to_csv('valid_phos_sensor_data.csv', index=False)

In [1]:
import pandas as pd

excel_negative = r"./phos_sensor_neg_data.txt"
df_negative = pd.read_csv(excel_negative, index_col=None, sep=",")
df_negative.to_csv('invalid_phos_sensor_data.csv', index=False)

In [2]:
import pandas as pd
import numpy as np

df_valid = pd.read_csv(r'./valid_phos_sensor_data.csv',
            index_col=None,
            names=["param_1", "param_2", "param_3", "param_4", "sensitivity"])
df_valid['infeasible'] = 0
df_actual_valid = df_valid.drop_duplicates()

df_invalid = pd.read_csv(r'./invalid_phos_sensor_data.csv',
                index_col=None,
                names=["param_1", "param_2", "param_3", "param_4"])
df_invalid['infeasible'] = 1
df_invalid['sensitivity'] = 0
df_actual_invalid = df_invalid.drop_duplicates()

df_actual = df_actual_valid.append(df_actual_invalid)
# df_actual_shuffled = df_actual.sample(frac=1)
# print(df_actual_shuffled)

df_sorted = df_actual.sort_values(by=["sensitivity"])
print(df_sorted)

train_len = int(0.8 * (len(df_sorted) - 1))
df_train = df_sorted.iloc[: train_len, :]
df_valid = df_sorted.iloc[train_len + 1 : , :]

training_data = df_train.to_dict('list')
validation_data = df_valid.to_dict('list')

# Making all the parameters discrete
for key in training_data:
    training_data[key] = np.array(training_data[key], dtype=np.float32)
training_data['param_2'] = np.array(int(1e2)*training_data['param_2'], dtype=np.int32)
training_data['param_2'] = np.array(training_data['param_2'], dtype=np.float32)
training_data['param_4'] = np.array(int(1e2)*training_data['param_4'], dtype=np.int32)
training_data['param_4'] = np.array(training_data['param_4'], dtype=np.float32) 
# Making all the parameters discrete
for key in validation_data:
    validation_data[key] = np.array(validation_data[key], dtype=np.float32)
validation_data['param_2'] = np.array(int(1e2)*validation_data['param_2'], dtype=np.int32)
validation_data['param_2'] = np.array(validation_data['param_2'], dtype=np.float32)
validation_data['param_4'] = np.array(int(1e2)*validation_data['param_4'], dtype=np.int32)
validation_data['param_4'] = np.array(validation_data['param_4'], dtype=np.float32) 

unique_list = []
for key in training_data:
    if key != 'sensitivity' and key !='infeasible':
        unique_list.append(np.unique(training_data[f'{key}']))
print(unique_list)
for element in unique_list:
    print(len(element))

print ('Keys in the dataset: ', training_data.keys())

      param_1  param_2  param_3  param_4  sensitivity  infeasible
692       750     0.73      240     1.00     0.000000           1
236       540     0.64      225     1.07     0.000000           1
235       540     0.64      225     1.05     0.000000           1
234       540     0.64      225     1.03     0.000000           1
233       530     0.73      240     1.00     0.000000           1
...       ...      ...      ...      ...          ...         ...
1121      660     0.67      195     1.07    43.373788           0
1013      620     0.70      180     1.05    43.848219           0
995       620     0.67      165     1.03    44.115221           0
855       600     0.70      165     1.03    44.400222           0
694       580     0.73      165     1.03    45.465227           0

[1872 rows x 6 columns]
[array([450., 460., 470., 480., 490., 500., 510., 520., 530., 540., 550.,
       560., 570., 580., 590., 600., 610., 620., 630., 640., 650., 660.,
       670., 680., 690., 700., 710., 720., 730., 740., 750.],
      dtype=float32), array([64., 67., 70., 73.], dtype=float32), array([165., 180., 195., 210., 225., 240.], dtype=float32), array([100., 101., 103., 104., 107., 109.], dtype=float32)]
31
4
6
6
Keys in the dataset:  dict_keys(['param_1', 'param_2', 'param_3', 'param_4', 'sensitivity', 'infeasible'])

/tmp/ipykernel_12222/2205826154.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_actual = df_actual_valid.append(df_actual_invalid)

In [2]:
training_data['infeasible']

array([1., 1., 1., ..., 0., 0., 0.], dtype=float32)

In [ ]:
# importing the required modules
import glob
import pandas as pd
 
# specifying the path to csv files
path = "/home/antragoudaras/prime_workspace/dataset_high_freq"
 
# csv files in the path
file_list = glob.glob(path + "/*.xlsx")
 
# list of excel files we want to merge.
# pd.read_excel(file_path) reads the 
# excel data into pandas dataframe.
excl_list = []
 
for file in file_list:
    excl_list.append(pd.read_excel(file))
 
# concatenate all DataFrames in the list
# into a single DataFrame, returns new
# DataFrame.
excl_merged = pd.concat(excl_list, ignore_index=True)
 
# exports the dataframe into excel file
# with specified name.
excl_merged.to_excel('./final_dataset_high_freq.xlsx', index=False)

In [1]:
# importing the required modules
import glob
import pandas as pd
 
# specifying the path to csv files
path = "/home/antragoudaras/prime_workspace/dataset_low_freq"
 
# csv files in the path
file_list = glob.glob(path + "/*.xlsx")
 
# list of excel files we want to merge.
# pd.read_excel(file_path) reads the 
# excel data into pandas dataframe.
excl_list = []
 
for file in file_list:
    excl_list.append(pd.read_excel(file))
 
# concatenate all DataFrames in the list
# into a single DataFrame, returns new
# DataFrame.
excl_merged = pd.concat(excl_list, ignore_index=True)
 
# exports the dataframe into excel file
# with specified name.
excl_merged.to_excel('./final_dataset_low_freq.xlsx', index=False)

In [4]:
import tensorflow as tf
import pandas as pd
import numpy as np
import random
from numpy.random import default_rng

2022-08-29 19:05:00.613475: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-29 19:05:00.613502: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [ ]:
read_file = pd.read_excel(r'/home/antragoudaras/prime_workspace/final_dataset_high_freq.xlsx')
read_file.to_csv(r'/home/antragoudaras/prime_workspace/final_dataset_high_freq.csv', index=None, header=True)

In [2]:
read_file = pd.read_excel(r'/home/antragoudaras/prime_workspace/final_dataset_low_freq.xlsx')
read_file.to_csv(r'/home/antragoudaras/prime_workspace/final_dataset_low_freq.csv', index=None, header=True)

In [7]:
df = pd.read_csv(r'/home/antragoudaras/prime_workspace/final_dataset_high_freq.csv',
            index_col=0,
            names=["param_1", "param_2", "param_3", "param_4", "param_5", "param_6", "param_7", "param_8", "accuracy"])

# Drop first row by selecting all rows from first row onwards
print(df)
df = df.iloc[1: , :]
print(df)
# df_actual = df.drop_duplicates()
# df_sorted = df_actual.sort_values(by=["accuracy"])
# print(df_sorted)

                   param_1             param_2         param_3  \
Unnamed: 0  n_filters_time  filter_time_length  n_filters_spat
0                       40                  25              40
1                       47                  11              53
2                       51                  29              35
3                       29                  23              37
...                    ...                 ...             ...
96                      37                  16              32
97                      52                  26              37
98                      25                  12              31
99                      53                  35              34
100                     46                  23              32

                     param_4           param_5             param_6  \
Unnamed: 0  pool_time_length  pool_time_stride           drop_prob
0                         75                15                 0.5
1                         54                12                 0.8
2                         69                10                 0.3
3                         52                23                 0.4
...                      ...               ...                 ...
96                        64                16                 0.5
97                        78                12                 0.4
98                        74                17                 0.8
99                        59                22                 0.2
100                       79                11  0.7000000000000002

                        param_7      param_8           accuracy
Unnamed: 0  learning_rate_range  decay_range           accuracy
0                        0.0625          0.0           71.91358
1                        0.0325     0.000675  70.17746913580247
2                        0.0425       0.0009  69.98456790123457
3                        0.0525    0.0007875  69.63734567901234
...                         ...          ...                ...
96                       0.0925    0.0001125  68.28703703703704
97                       0.0825    0.0005625  69.36728395061726
98                       0.0225       0.0009  71.52777777777777
99                       0.0425    0.0003375  67.05246913580247
100                      0.0925      0.00045   70.7175925925926

[8081 rows x 9 columns]
    param_1 param_2 param_3 param_4 param_5             param_6 param_7  \
0        40      25      40      75      15                 0.5  0.0625
1        47      11      53      54      12                 0.8  0.0325
2        51      29      35      69      10                 0.3  0.0425
3        29      23      37      52      23                 0.4  0.0525
4        49      26      27      75      25  0.6000000000000001  0.0225
..      ...     ...     ...     ...     ...                 ...     ...
96       37      16      32      64      16                 0.5  0.0925
97       52      26      37      78      12                 0.4  0.0825
98       25      12      31      74      17                 0.8  0.0225
99       53      35      34      59      22                 0.2  0.0425
100      46      23      32      79      11  0.7000000000000002  0.0925

       param_8           accuracy
0          0.0           71.91358
1     0.000675  70.17746913580247
2       0.0009  69.98456790123457
3    0.0007875  69.63734567901234
4     0.000225   70.7175925925926
..         ...                ...
96   0.0001125  68.28703703703704
97   0.0005625  69.36728395061726
98      0.0009  71.52777777777777
99   0.0003375  67.05246913580247
100    0.00045   70.7175925925926

[8080 rows x 9 columns]

In [ ]:
print(len(df_sorted))

In [ ]:
train_len = int(0.8 * (len(df_sorted) - 1))
df_train = df_sorted.iloc[: train_len, :]
df_valid = df_sorted.iloc[train_len + 1 : , :]

In [ ]:
generic_data = df_sorted.to_dict('list')

In [ ]:
for key in generic_data:
    generic_data[key] = np.array(generic_data[key], dtype=np.float32)

In [ ]:
generic_data['param_6'] = np.array(int(1e1)*generic_data['param_6'], dtype=np.float32)
generic_data['param_7'] = np.array(int(1e2)*generic_data['param_7'], dtype=np.int32)
generic_data['param_7'] = np.array(generic_data['param_7'], dtype=np.float32)
generic_data['param_8'] = np.array(int(1e4)*generic_data['param_8'], dtype=np.int32)
generic_data['param_8'] = np.array(generic_data['param_8'], dtype=np.float32)

In [ ]:
unique_list = []
for key in generic_data:
    if key != 'accuracy':
        unique_list.append(np.unique(generic_data[f'{key}']))
print(unique_list)

In [ ]:
for arr in unique_list:
    print(len(arr))

In [ ]:
validation_data = np.array([[43., 22., 33., 65., 18.,  7.,  1.,  5.],
 [26., 34., 27., 53., 14.,  7.,  4.,  7.],
 [43., 34., 25., 50., 14.,  8.,  7.,  4.],
 [35., 26., 28., 50., 14.,  8.,  6.,  4.],
 [35., 12., 29., 58., 14.,  7.,  1.,  6.],
 [34., 35. ,33., 73., 20.,  7.,  2.,  2.],
 [25., 20., 27., 50., 14.,  8.,  4.,  1.],
 [35., 19., 43., 51., 16.,  7.,  4.,  2.],
 [37., 28., 33., 56., 14.,  7.,  5.,  6.],
 [35., 15., 43., 51., 18.,  7.,  5.,  4.],
 [25., 34., 34., 50., 14.,  8.,  4.,  7.],
 [37., 27., 38., 50., 14.,  8.,  2.,  7.],
 [26., 28., 33., 51., 20.,  7.,  1.,  2.],
 [49., 35., 25., 50., 14.,  7.,  4.,  1.],
 [25., 35., 43., 50., 16.,  7.,  4.,  7.],
 [35., 28., 40., 51., 12.,  7.,  4.,  7.],
 [25., 20., 25., 50., 14.,  8.,  2.,  1.],
 [25., 28., 33., 51., 11.,  7.,  5.,  0.],
 [44., 14., 51., 70., 14.,  7.,  2.,  7.],
 [26., 28., 27., 50., 16.,  8.,  4.,  4.],
 [26., 16., 39., 51., 14.,  7.,  2.,  4.],
 [29., 23., 32., 50., 14.,  8.,  4.,  7.],
 [25., 13., 33., 50., 11.,  8.,  1.,  9.],
 [25., 34., 33., 65., 24.,  7. , 4.,  1.],
 [49., 27., 33., 50., 14.,  8., 4.,  1.]])

In [ ]:
validation_dataset = pd.DataFrame({'param_1': validation_data[:, 0], 'param_2': validation_data[:, 1], 'param_3': validation_data[:, 2], 
                        'param_4': validation_data[:, 3], 'param_5': validation_data[:, 4], 'param_6': validation_data[:, 5], 
                        'param_7': validation_data[:, 6], 'param_8': validation_data[:, 7]})

In [ ]:
param_7_series = validation_dataset['param_7'].squeeze()

In [ ]:
param_8_series = validation_dataset['param_8'].squeeze()

In [ ]:
validation_dataset['param_7'] = param_7_series.map({1: 0.0125, 2: 0.0225, 3: 0.0325, 4: 0.0425, 5: 0.0525, 6: 0.0625, 7: 0.0725, 8: 0.0825, 9: 0.0925})
validation_dataset['param_8'] = param_8_series.map({0: 0, 1: 0.00011, 2: 0.00023, 3: 0.00034, 4: 0.00045, 5: 0.00056, 6: 0.00068, 7: 0.00079, 9: 0.0009})

In [ ]:
validation_dataset.to_csv('./validation_set_optimized_high_freq.csv')

In [ ]:
validation_dataset.to_excel('./validation_set_optimized_high_freq.xlsx')

In [ ]:
training_data = np.array([[43., 35., 33., 70., 14.,  7.,  1.,  3.],
 [50., 24., 40., 52., 14.,  7.,  1.,  2.],
 [25., 17., 37., 51., 14.,  7.,  7.,  7.],
 [26., 28., 28., 51., 24.,  7.,  4.,  4.],
 [25., 35., 25., 73., 14.,  7.,  4.,  7.],
 [35., 34., 41., 73., 20.,  7.,  2.,  7.],
 [41., 28., 40., 51., 18.,  7.,  2.,  7.],
 [37., 14., 37., 59., 18.,  7.,  1.,  4.],
 [25., 22., 29., 51., 14.,  7.,  1.,  4.],
 [47., 14., 33., 65., 18.,  7.,  4.,  1.],
 [54., 35., 45., 70., 14.,  7.,  2.,  1.],
 [25., 35., 33., 65., 18.,  7.,  5.,  4.],
 [25., 18., 32., 50., 14.,  8.,  2.,  4.],
 [30., 14., 42., 50., 14.,  8.,  4.,  7.],
 [25., 34., 29., 50., 14.,  8.,  4.,  4.],
 [25., 26., 41., 50., 14.,  8.,  2.,  2.],
 [51., 34., 43., 51., 14.,  7.,  5.,  4.],
 [25., 17., 34., 50., 14.,  8.,  4.,  7.],
 [35., 10., 39., 66., 14.,  7.,  4.,  6.],
 [35., 26., 40., 55., 14.,  7.,  1.,  6.],
 [35., 31., 25., 50., 11.,  8.,  4.,  4.],
 [25., 20., 33., 51., 14.,  6.,  4.,  4.],
 [49., 28., 25., 50., 14.,  8.,  1.,  4.],
 [25., 28., 25., 50., 14.,  8.,  1.,  6.],
 [35., 20., 40., 70., 20.,  7.,  2.,  1.]])

In [ ]:
training_dataset = pd.DataFrame({'param_1': training_data[:, 0], 'param_2': training_data[:, 1], 'param_3': training_data[:, 2], 
                        'param_4': training_data[:, 3], 'param_5': training_data[:, 4], 'param_6': training_data[:, 5], 
                        'param_7': training_data[:, 6], 'param_8': training_data[:, 7]})

In [ ]:
param_7_series = training_dataset['param_7'].squeeze()
param_8_series = training_dataset['param_8'].squeeze()

In [ ]:
training_dataset['param_7'] = param_7_series.map({1: 0.0125, 2: 0.0225, 3: 0.0325, 4: 0.0425, 5: 0.0525, 6: 0.0625, 7: 0.0725, 8: 0.0825, 9: 0.0925})
training_dataset['param_8'] = param_8_series.map({0: 0, 1: 0.00011, 2: 0.00023, 3: 0.00034, 4: 0.00045, 5: 0.00056, 6: 0.00068, 7: 0.00079, 9: 0.0009})

In [ ]:
training_dataset

In [ ]:
training_dataset.to_csv('./training_set_optimized_high_freq.csv')

In [ ]:
training_dataset.to_excel('./training_set_optimized_high_freq.xlsx')

In [2]:
random_data = np.array([[38., 16., 27., 56., 14.,  7.,  1.,  4.],
 [26., 15., 33., 51., 24.,  7.,  4.,  2.],
 [51., 12., 40., 51., 14.,  7.,  2.,  2.],
 [25., 28., 40., 73., 24.,  7.,  2.,  7.],
 [25., 31., 48., 51., 14.,  8.,  1.,  7.],
 [41., 17., 33., 50., 14.,  8.,  4.,  2.],
 [25., 14., 33., 65., 16.,  7.,  4.,  7.],
 [35., 22., 40., 52., 14.,  7.,  5.,  7.],
 [51., 22., 51., 51., 14.,  7.,  5.,  4.],
 [27., 25., 40., 51., 14.,  7.,  1.,  0.],
 [26., 34., 33., 51., 16.,  7.,  2.,  0.],
 [25., 35., 27., 50., 24.,  7.,  5.,  4.],
 [26., 24., 40., 51., 14.,  7.,  1.,  6.],
 [25., 34., 27., 50., 14.,  8.,  1.,  3.],
 [35., 34., 40., 69., 20.,  7.,  2.,  2.],
 [25., 10., 33., 50., 11.,  8.,  1.,  4.],
 [37., 34., 32., 66., 24.,  8.,  1.,  2.],
 [26., 35., 27., 55., 14.,  7. , 6.,  4.],
 [51., 12., 34., 51., 14.,  7.,  1.,  3.],
 [35., 10., 47., 69., 14.,  7.,  2.,  7.],
 [35., 30., 27., 52., 14.,  7.,  3.,  4.],
 [41., 24., 33., 50., 14.,  7.,  2.,  9.],
 [40., 35., 33., 65., 18.,  7.,  4.,  4.],
 [25., 23., 33., 51., 18.,  7.,  4.,  7.],
 [47., 28., 39., 51., 16.,  7.,  1.,  7.]])

In [3]:
random_dataset = pd.DataFrame({'param_1': random_data[:, 0], 'param_2': random_data[:, 1], 'param_3': random_data[:, 2], 
                        'param_4': random_data[:, 3], 'param_5': random_data[:, 4], 'param_6': random_data[:, 5], 
                        'param_7': random_data[:, 6], 'param_8': random_data[:, 7]})

In [4]:
param_7_series = random_dataset['param_7'].squeeze()
param_8_series = random_dataset['param_8'].squeeze()

In [5]:
random_dataset['param_7'] = param_7_series.map({1: 0.0125, 2: 0.0225, 3: 0.0325, 4: 0.0425, 5: 0.0525, 6: 0.0625, 7: 0.0725, 8: 0.0825, 9: 0.0925})
random_dataset['param_8'] = param_8_series.map({0: 0, 1: 0.00011, 2: 0.00023, 3: 0.00034, 4: 0.00045, 5: 0.00056, 6: 0.00068, 7: 0.00079, 9: 0.0009})

In [6]:
random_dataset

    param_1  param_2  param_3  param_4  param_5  param_6  param_7  param_8
0      38.0     16.0     27.0     56.0     14.0      7.0   0.0125  0.00045
1      26.0     15.0     33.0     51.0     24.0      7.0   0.0425  0.00023
2      51.0     12.0     40.0     51.0     14.0      7.0   0.0225  0.00023
3      25.0     28.0     40.0     73.0     24.0      7.0   0.0225  0.00079
4      25.0     31.0     48.0     51.0     14.0      8.0   0.0125  0.00079
5      41.0     17.0     33.0     50.0     14.0      8.0   0.0425  0.00023
6      25.0     14.0     33.0     65.0     16.0      7.0   0.0425  0.00079
7      35.0     22.0     40.0     52.0     14.0      7.0   0.0525  0.00079
8      51.0     22.0     51.0     51.0     14.0      7.0   0.0525  0.00045
9      27.0     25.0     40.0     51.0     14.0      7.0   0.0125  0.00000
10     26.0     34.0     33.0     51.0     16.0      7.0   0.0225  0.00000
11     25.0     35.0     27.0     50.0     24.0      7.0   0.0525  0.00045
12     26.0     24.0     40.0     51.0     14.0      7.0   0.0125  0.00068
13     25.0     34.0     27.0     50.0     14.0      8.0   0.0125  0.00034
14     35.0     34.0     40.0     69.0     20.0      7.0   0.0225  0.00023
15     25.0     10.0     33.0     50.0     11.0      8.0   0.0125  0.00045
16     37.0     34.0     32.0     66.0     24.0      8.0   0.0125  0.00023
17     26.0     35.0     27.0     55.0     14.0      7.0   0.0625  0.00045
18     51.0     12.0     34.0     51.0     14.0      7.0   0.0125  0.00034
19     35.0     10.0     47.0     69.0     14.0      7.0   0.0225  0.00079
20     35.0     30.0     27.0     52.0     14.0      7.0   0.0325  0.00045
21     41.0     24.0     33.0     50.0     14.0      7.0   0.0225  0.00090
22     40.0     35.0     33.0     65.0     18.0      7.0   0.0425  0.00045
23     25.0     23.0     33.0     51.0     18.0      7.0   0.0425  0.00079
24     47.0     28.0     39.0     51.0     16.0      7.0   0.0125  0.00079

In [7]:
random_dataset.to_csv('./random_set_optimized_high_freq.csv')

In [8]:
random_dataset.to_excel('./random_set_optimized_high_freq.xlsx')

In [3]:
validation_data = np.array([[25., 31., 42., 50., 28.,  4.,  1.,  9.],
 [26., 28., 42., 57., 28.,  5.,  1.,  9.],
 [28., 17., 29., 82., 28.,  6.,  1.,  7.],
 [34., 17., 47., 69., 28.,  5.,  1.,  3.],
 [28., 17., 27., 56., 28.,  5.,  2.,  7.],
 [36., 17., 42., 69., 28.,  4.,  1.,  7.],
 [46., 27., 44., 57., 28.,  4.,  2.,  6.],
 [36., 20., 53., 69., 28.,  4.,  1.,  1.],
 [28., 12., 42., 56., 28.,  4.,  1.,  1.],
 [28., 31., 35., 56., 28.,  5.,  2.,  5.],
 [26., 17., 31., 54., 28.,  5.,  1.,  5.],
 [30., 16., 35., 82., 28.,  5.,  1.,  4.],
 [28., 17., 49., 56., 28.,  6.,  1.,  9.],
 [38., 21., 42., 69., 28.,  5.,  1.,  4.],
 [25., 17., 38., 67., 28.,  6.,  2.,  7.],
 [26., 20., 33., 67., 28.,  4.,  4.,  4.],
 [28., 16., 33., 56., 28.,  6.,  1.,  5.],
 [33., 27., 43., 69., 28.,  5.,  1.,  7.],
 [36., 17., 48., 70., 28.,  6.,  1.,  4.],
 [25., 11., 48., 82., 28.,  5.,  1.,  6.],
 [28., 16., 42., 56., 28.,  5.,  2.,  4.],
 [25., 27., 33., 50., 28.,  8.,  1.,  7.],
 [30., 17., 28., 56., 28.,  5.,  1.,  7.],
 [26., 16., 48., 58., 28.,  6.,  1.,  5.],
 [34., 31., 31., 57., 28.,  4.,  2.,  2.]])

In [4]:
validation_dataset = pd.DataFrame({'param_1': validation_data[:, 0], 'param_2': validation_data[:, 1], 'param_3': validation_data[:, 2], 
                        'param_4': validation_data[:, 3], 'param_5': validation_data[:, 4], 'param_6': validation_data[:, 5], 
                        'param_7': validation_data[:, 6], 'param_8': validation_data[:, 7]})

In [5]:
param_7_series = validation_dataset['param_7'].squeeze()
param_8_series = validation_dataset['param_8'].squeeze()

In [6]:
validation_dataset['param_7'] = param_7_series.map({1: 0.0125, 2: 0.0225, 3: 0.0325, 4: 0.0425, 5: 0.0525, 6: 0.0625, 7: 0.0725, 8: 0.0825, 9: 0.0925})
validation_dataset['param_8'] = param_8_series.map({0: 0, 1: 0.00011, 2: 0.00023, 3: 0.00034, 4: 0.00045, 5: 0.00056, 6: 0.00068, 7: 0.00079, 9: 0.0009})

In [7]:
validation_dataset

    param_1  param_2  param_3  param_4  param_5  param_6  param_7  param_8
0      25.0     31.0     42.0     50.0     28.0      4.0   0.0125  0.00090
1      26.0     28.0     42.0     57.0     28.0      5.0   0.0125  0.00090
2      28.0     17.0     29.0     82.0     28.0      6.0   0.0125  0.00079
3      34.0     17.0     47.0     69.0     28.0      5.0   0.0125  0.00034
4      28.0     17.0     27.0     56.0     28.0      5.0   0.0225  0.00079
5      36.0     17.0     42.0     69.0     28.0      4.0   0.0125  0.00079
6      46.0     27.0     44.0     57.0     28.0      4.0   0.0225  0.00068
7      36.0     20.0     53.0     69.0     28.0      4.0   0.0125  0.00011
8      28.0     12.0     42.0     56.0     28.0      4.0   0.0125  0.00011
9      28.0     31.0     35.0     56.0     28.0      5.0   0.0225  0.00056
10     26.0     17.0     31.0     54.0     28.0      5.0   0.0125  0.00056
11     30.0     16.0     35.0     82.0     28.0      5.0   0.0125  0.00045
12     28.0     17.0     49.0     56.0     28.0      6.0   0.0125  0.00090
13     38.0     21.0     42.0     69.0     28.0      5.0   0.0125  0.00045
14     25.0     17.0     38.0     67.0     28.0      6.0   0.0225  0.00079
15     26.0     20.0     33.0     67.0     28.0      4.0   0.0425  0.00045
16     28.0     16.0     33.0     56.0     28.0      6.0   0.0125  0.00056
17     33.0     27.0     43.0     69.0     28.0      5.0   0.0125  0.00079
18     36.0     17.0     48.0     70.0     28.0      6.0   0.0125  0.00045
19     25.0     11.0     48.0     82.0     28.0      5.0   0.0125  0.00068
20     28.0     16.0     42.0     56.0     28.0      5.0   0.0225  0.00045
21     25.0     27.0     33.0     50.0     28.0      8.0   0.0125  0.00079
22     30.0     17.0     28.0     56.0     28.0      5.0   0.0125  0.00079
23     26.0     16.0     48.0     58.0     28.0      6.0   0.0125  0.00056
24     34.0     31.0     31.0     57.0     28.0      4.0   0.0225  0.00023

In [8]:
validation_dataset.to_csv('./validation_set_optimized_low_freq.csv')

In [9]:
validation_dataset.to_excel('./validation_set_optimized_low_freq.xlsx')

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'./final_dataset_high_freq.csv',
            index_col=0,
            names=["param_1", "param_2", "param_3", "param_4", "param_5", "param_6", "param_7", "param_8", "accuracy"])

# Drop first row by selecting all rows from first row onwards
df = df.iloc[1: , :]
df_actual = df.drop_duplicates()
df_sorted = df_actual.sort_values(by=["accuracy"])
print(df_sorted)

train_len = int(0.8 * (len(df_sorted) - 1))
df_train = df_sorted.iloc[: train_len, :]
df_valid = df_sorted.iloc[train_len + 1 : , :]

training_data = df_train.to_dict('list')
validation_data = df_valid.to_dict('list')

# Making all the parameters discrete
for key in training_data:
    training_data[key] = np.array(training_data[key], dtype=np.float32)
training_data['param_6'] = np.array(int(1e1)*training_data['param_6'], dtype=np.float32)
training_data['param_7'] = np.array(int(1e2)*training_data['param_7'], dtype=np.int32)
training_data['param_7'] = np.array(training_data['param_7'], dtype=np.float32)
training_data['param_8'] = np.array(int(1e4)*training_data['param_8'], dtype=np.int32)
training_data['param_8'] = np.array(training_data['param_8'], dtype=np.float32) 
# Making all the parameters discrete
for key in validation_data:
    validation_data[key] = np.array(validation_data[key], dtype=np.float32)
validation_data['param_6'] = np.array(int(1e1)*validation_data['param_6'], dtype=np.float32)
validation_data['param_7'] = np.array(int(1e2)*validation_data['param_7'], dtype=np.int32)
validation_data['param_7'] = np.array(validation_data['param_7'], dtype=np.float32)
validation_data['param_8'] = np.array(int(1e4)*validation_data['param_8'], dtype=np.int32)
validation_data['param_8'] = np.array(validation_data['param_8'], dtype=np.float32)

    param_1 param_2 param_3 param_4 param_5 param_6 param_7    param_8  \
47       43      31      52      81      27     0.2  0.0725        0.0
41       30      32      41      80      29     0.2  0.0325    0.00045
16       43      35      34      76      28     0.2  0.0725        0.0
12       46      31      43      79      27     0.2  0.0925  0.0003375
66       34      22      37      78      29     0.2  0.0925     0.0009
..      ...     ...     ...     ...     ...     ...     ...        ...
46       44      20      30      53      29     0.8  0.0225  0.0003375
44       38      31      34      66      29     0.8  0.0125  0.0003375
100      25      21      32      57      29     0.8  0.0325  0.0007875
29       35      30      32      77      29     0.8  0.0225  0.0003375
63       36      30      31      51      29     0.8  0.0225        0.0

              accuracy
47   62.34567901234568
41                62.5
16   62.80864197530865
12   62.84722222222222
66   62.96296296296296
..                 ...
46   74.76851851851852
44   74.76851851851852
100               75.0
29   75.34722222222223
63   75.69444444444444

[8001 rows x 9 columns]

In [3]:
training_data["param_6"]

array([2., 2., 2., ..., 7., 6., 8.], dtype=float32)